name: SP_GroupManager
version: '1'
main: SPGroupManager.SPGroupManager
api-version: 1.19
authors: [ Gnaris ]
depend: [SP_Database]
commands:
  spgroup:
permissions:
  sperias.group.command.spgroup:
    description: "Manage group"