name: GroupManager
version: '1'
main: GroupManager.GroupManager
api-version: 1.19
authors: [ Gnaris ]
depend: [SP_Database]
commands:
  group:
permissions:
  sperias.group.command.group:
    description: "Manage group"